config/routes.rb
Localhost::Application.routes.draw do
  
  match '/auth/:provider/callback' => 'sessions#create'
  
  match '/signout' => 'sessions#destroy'
  
  resources :authentications
  resources :reviews
  resources :friendships
  resources :users
  resources :sessions
  resources :food

  get "logout" => "sessions#destroy", :as => "logout"

  root :to => "homepage#index"
  
 

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_one :profile
  
  has_many :assignments, :dependent => :destroy
  has_many :roles, :through => :assignments
  
  has_many :friendships, :dependent => :destroy
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", :dependent => :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  
  has_many :reviews
  has_many :reviews_written, :class_name => "Review", :foreign_key => 'reviewer_id'
  has_many :reviews_about, :class_name => "Review", :foreign_key => 'reviewee_id'

  
  has_many :food_relationships
 
  has_many :food_exclusions, :through => :food_relationships, :class_name => "Food", :foreign_key => "user_id", :conditions => ["inclusion = ?", false] 
  has_many :food_inclusions, :through => :food_relationships, :class_name => "Food", :foreign_key => "user_id", :conditions => ["inclusion = ?", true]

  attr_accessible :email
  
  after_create :create_role
  
  # validates_confirmation_of :password
  #   validates_presence_of :password, :on => :create, :message => "Password can't be blank"
  # validates_presence_of :email, :on => :create, :message => "Email can't be blank"
  #   validates_uniqueness_of :email, :on => :create, :message => "This email address is already registered"
  
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
  
  def rating
    # Returns an average user rating based on 
    # rating input, converts it to a 1-20 scale
    if self.reviews_about.nil?
      return 0
    else
      reviews = self.reviews_about
      totalscore = 0
      reviews.each do |review|
        totalscore += review.rating
      end
      return totalscore if totalscore == 0
      return ((totalscore.to_f/reviews.length)*4).to_i
    end
  end
  
  def self.create_with_omniauth(auth)
    if auth["info"]["location"]
      location = auth["info"]["location"]
      (city, state) = location.split(/,/)
      city = city.strip
      state = state.strip
    end
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.first_name = auth["info"]["first_name"]
      user.last_name = auth["info"]["last_name"]
      user.city = city
      user.state = state
      user.facebook_url = auth["info"]["urls"]["Facebook"]
      user.gender = auth["extra"]["raw_info"]["gender"] 
    end
  end
  
  def create_role
    Assignment.create :user => self, :role => Role.find_by_name("user")
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, except: [:new, :create, :show]

  filter_access_to :edit, :update, :attribute_check => true
  
  def index
      @user = User.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @user }
      end
  end
    
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @user}
    end
  end
  
  def edit
      @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: "User was successfully deleted."
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_rating.html.erb
<div class="Clear">
	<div class="star-rating-readonly"></div>
	<% 	counter = 0 %>
	<% offset = [0, -4, -8, -13] %>
	<% (1..@user.rating).each do |num| %>
		<% counter = 0 if counter == 4 %>
		<div class="star-rating rater-5 star {split:4} star-rating-applied star-rating-readonly star-rating-on" style="width: 4px;">
			<span class="star-rating-control"><a title="<%= num %>" style="margin-left: <%= offset[counter] %>px;"><%= num %></a></span>
		</div>
		<% counter+= 1 %>
	<% end %>
	
	<% (@user.rating+1..20).each do |num| %>
		<% counter = 0 if counter == 4 %>
		<div class="star-rating rater-5 star {split:4} star-rating-applied star-rating-readonly" style="width: 4px;">
			<span class="star-rating-control"><a title="<%= num %>" style="margin-left: <%= offset[counter] %>px;"><%= num %></a></span>
		</div>
		<% counter+= 1 %>
	<% end %>
</div>

app/views/users/_rating2.html.erb
<div class="Clear">
	<% counter = 0 %>
	<% offset = [0, -4, -8, -13] %>
	<ul>
	<% (1..@user.rating).each do |num| %>
		<% counter = 0 if counter == 4 %>
		<li><%= num %> <%= offset[counter] %> <%= counter %> on</li>
		<% counter+= 1 %>
	<% end %>
	
	<% (@user.rating+1..20).each do |num| %>
		<% counter = 0 if counter == 4 %>
		<li><%= num %> <%= offset[counter] %> <%= counter %> off</li>
		<% counter+= 1 %>
	<% end %>
	
	</ul>
</div>

app/views/users/edit.html.erb
<%= form_for @user, :html => {:multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="alert-message error">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
  	<h3>Here's what we know about you...</h3>
	<ul class="unstyled">
		<li>Email Address: <%= @user.email %></li>
		<li>Name: <%= @user.name %></li>
		<% if @user.city %>
    		<li>City: <%= @user.city %></li>
		<% else %>
			<li>City: <i>no city specified</i></li>
		<% end %>
		
		<% if @user.state %>
    		<li>State: <%= @user.state %></li>
		<% else %>
			<li>State: <i>no state specified</i></li>
		<% end %>
		
	    <li>&nbsp;</li>
		<% if permitted_to? :edit, @user.roles %>
			<% for role in Role.all %>
				<%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
				<%=h role.name %><br />
			<% end %>
		<% end %>
		<li><%= f.submit 'Submit', :class=> "btn" %></li>
	</ul>
    
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Email</th>
  <th>Role</th>
  <th></th>
  <th></th>
  </tr>

<% @user.each do |user| %>
    <tr>
      <td><%= link_to "#{user.name}", user %></td>
      <td><%= user.email%></td>
      <td><% user.roles.each do |role| %><%= role.name %> <% end %></td>
	 <td> <% if permitted_to? :edit, user %>
      		<%= link_to 'Edit User', edit_user_path(user) %>
      	  <% end %></td>
	<td><% if permitted_to? :delete, user %>
      		<%= link_to 'Delete User', user, confirm: 'Are you sure?', method: :delete %>
    	<% end %></td>
    </tr>
<% end %>
</table>

app/views/users/new.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
	<% if @user.errors.any? %>
		<div class="alert-message error">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
					
				<% end %>
			</ul>
		</div>
	<% end %>
		<div class="field">
			<ul class="unstyled">
				<li><%= f.label :username %> <%= f.text_field :username %></li>
				<li><%= f.label :email %> <%= f.text_field :email %></li>
				<li><%= f.label :password %> <%= f.password_field :password %></li>
				<li><%= f.label :password_confirmation %> <%= f.password_field :password_confirmation %></li>
				<li><%= f.label :profilepic %> <%= f.file_field :profilepic %></li>
				<% for role in Role.all %>
				      <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
				      <%=h role.name %><br />
				<% end %>
				<li><%= f.submit 'Submit', :class=> "btn" %></li>
			</ul>
		</div>
<% 	end %>

app/views/users/show.html.erb
<% if @user.errors.any? %>
	<div id="alert-message error">
	  <% @user.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
<% end %>
<% if @user != current_user %>
	<div class="pull-right">
		<p><%= link_to "Write a review for this user", new_review_path(:reviewee_id => params[:id]) %></p>
	</div>
<% end %>
<div class="row">
	<div class="span4">
		<div class="row">
			<ul class="unstyled">
		    <li><h2><%= @user.name %></li></h2>
			<li><%= @user.city %>, <%= @user.state %></li>
			<%= link_to image_tag("http://graph.facebook.com/#{@user.uid}/picture?type=square", :border => 1), @user.facebook_url %>
				<% if permitted_to? :edit, @user %>
					<li><%= link_to "Edit account", edit_user_path %></li>
				<% end %>
				</ul>
				<p>Average Rating:</p> <%= render "rating" %><br>
				<% if @user != current_user %>
					<% unless current_user.friends.find_by_id(@user) %>
				    	<p><%= link_to "Add Friendship", friendships_path(:friend_id => @user), :method => :post %></p>		
					<% else %>
						<p><%= @user.name %> is a friend.</p>
				    <% end %>
				<% end %>
				
		</div>
		<div class="row">
			<h3>Friends</h3>
			  <ul>
			      <% @user.friendships.each do |friendship| %>
			        <li><%= link_to friendship.friend.name, user_path(friendship.friend.id) %> 
						<% if permitted_to? :destroy, friendship %>
							(<%= link_to "remove", friendship, :method => :delete %>)
						<% end %>
					</li>
			      <% end %>

			  </ul>
		</div>
		<div class="row">
			<h3>Reviews by <%= @user.first_name %></h3>
			  <ul>
			      <% @user.reviews_written.each do |review| %> 
			        <li><%= link_to review.title, review %></li>
			      <% end %>
			  </ul>
		</div>
	</div>
	<div class="span12">
		<div class="row">
		  	<% @user.reviews_about.each do |review| %> 
		        <div class="span8">
					<h3><%= link_to review.title, review %></h3>
					<p class="small">written by <%= link_to "#{review.reviewer.name}", user_path(review.reviewer) %></p>
					<p><%=h truncate(review.body, :length => 250, :omission => '...(continued)') %></p>
					<hr>
				</div>
		      <% end %>
		</div>
	</div>

</div>