config/routes.rb
Localhost::Application.routes.draw do
  
  match '/auth/:provider/callback' => 'sessions#create'
  
  match '/signout' => 'sessions#destroy'
  
  resources :authentications
  resources :reviews
  resources :friendships
  resources :users
  resources :sessions
  resources :food

  get "logout" => "sessions#destroy", :as => "logout"

  root :to => "homepage#index"
  
 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  filter_resource_access
  before_filter :require_login, except: :show
  
  def new
    @review = Review.new
  end
  
  def create
    @review = Review.new(params[:review])
    @review.reviewer = current_user
    @review.user = @review.reviewer
    if @review.save
      redirect_to user_url(@review.reviewee), :notice => "Successfully created review."
    else
      render :action => 'new'
    end
  end
  
  def edit
    @review = Review.find(params[:id])
  end
  
  def update
    @review = Review.find(params[:id])
    @review.reviewer = current_user
    @review.user = @review.reviewer
    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to review_path(@review), notice: 'Review was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @review = Review.find(params[:id])
    respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @product }
    end  
  end
  
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to root_url, :notice => "Successfully destroyed review."
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper 

end

app/views/reviews/_form.html.erb
<%= form_for @review, :html => {:class => "form-stacked"} do |f| %>
  
  <div class="clearfix">
	<%= f.hidden_field :reviewee_id, :value => params[:reviewee_id] %>
    <p><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>
	<p><%= f.label :rating %></p>
	<p><%= f.select :rating, options_for_select(["1", "2", "3", "4", "5"]) %></p>
	<p><%= f.label :body %></p>
    <p><%= f.text_area :body, :class => "xlarge" %></p>
    <p><%= f.submit "Submit Review" %></p>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<%= form_for @review, :html => {:class => "form-stacked"} do |f| %>
  
  <div class="clearfix">
	<%= f.hidden_field :reviewee_id, :value => params[:reviewee_id] %>
    <p><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>
	<p><%= f.label :rating %></p>
	<p><%= f.select :rating, options_for_select(["1", "2", "3", "4", "5"]) %></p>
	<p><%= f.label :body %></p>
    <p><%= f.text_area :body, :class => "xlarge" %></p>
    <p><%= f.submit "Submit Review" %></p>
  </div>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p> 

<div class="actions">
	<div class="pull-right">
		<% if permitted_to? :edit, @review %>
			<%= link_to "Edit this review", edit_review_path(:reviewee_id => @review.reviewee_id) %>
		<% end %>
	</div>
	<div class="review">
		<p>This review is about: <%= link_to @review.reviewee.name, user_path(@review.reviewee)%></p>
		<p>Rating: <%= @review.rating %></p>
		<p class="review-title"><%= @review.title %></p>
		<p class="review-body"><%= @review.body %></p>
		<br>
		<p>Reviewed By: <%= link_to @review.reviewer.name, user_path(@review.reviewer) %></p>
		<p>on: <%= @review.created_at.to_s %>
	</div>
</div>